# Generated by Django 4.2.3 on 2023-07-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YarnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GTIN', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('needle_size', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=200)),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='webresource',
            name='item',
        ),
        migrations.AddField(
            model_name='webresource',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webresource',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='webresource',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='webresource',
            name='yarn_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources',
                                    to='scraping.yarnproduct'),
            preserve_default=False,
        ),
    ]
