# Generated by Django 4.2.3 on 2023-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scraping', '0002_yarnproduct_remove_webresource_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webresource',
            name='url',
            field=models.URLField(),
        ),
    ]
