# Generated by Django 4.2.3 on 2023-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scraping', '0003_alter_webresource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarnproduct',
            name='historical_lowest_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
