# Generated by Django 4.2.3 on 2023-07-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scraping', '0004_yarnproduct_historical_lowest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webresource',
            name='available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='yarnproduct',
            name='GTIN',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='yarnproduct',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yarnproduct',
            name='composition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yarnproduct',
            name='needle_size',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
